name: Setup
inputs:
  build:
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    - name: Install Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        npm install

    - name: Build
      if: ${{ inputs.build }}
      shell: bash
      run: |
        npm run build
