name: Formatting

on: [push, pull_request]

jobs:
  Setup:
    uses: ianmitchell/interaction-kit/.github/workflows/setup.yml@$GITHUB_SHA

  Prettier:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Formatting
        run: |
          yarn prettier
