name: Formatting

on: [push, pull_request]

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Formatting
        run: |
          npm run prettier
