name: Typecheck

on:
  workflow_call:

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install
        env:
          CI: true
        run: |
          npm install
