name: Lint

on: [push, pull_request]

jobs:
  Install:
    uses: ./.github/workflows/install.yml@v1

  Build:
    uses: ./.github/workflows/build.yml@v1

  ESLint:
    runs-on: ubuntu-latest
    needs:
      - Install
      - Build
    steps:
      - name: Lint
        run: |
          yarn lint

  Prettier:
    runs-on: ubuntu-latest
    needs:
      - Install
    steps:
      - name: Formatting
        run: |
          yarn prettier
