name: Lint

on: [push, pull_request]

jobs:
  Setup:
    uses: ianmitchell/interaction-kit/.github/workflows/setup.yml@$GITHUB_SHA
    with:
      build: true

  ESLint:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Lint
        run: |
          yarn lint
