name: Lint

on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      uses: ianmitchell/interaction-kit/.github/workflows/install.yml@v1

      uses: ianmitchell/interaction-kit/.github/workflows/build.yml@v1

      - name: Lint
        run: |
          yarn lint

  Prettier:
    runs-on: ubuntu-latest
    steps:
      uses: ianmitchell/interaction-kit/.github/workflows/install.yml@v1

      - name: Formatting
        run: |
          yarn prettier
