name: Setup

on:
  workflow_call:
    inputs:
      build:
        type: boolean
        default: false

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install
        env:
          CI: true
        run: |
          npm install

      - name: Build
        if: ${{ inputs.build }}
        run: |
          npm run build
