name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: ianmitchell/interaction-kit/.github/workflows/install.yml@v1

      - uses: ianmitchell/interaction-kit/.github/workflows/build.yml@v1

      - name: Test
        run: |
          npm test
