name: Test

on: [push, pull_request]

jobs:
  Install:
    uses: ianmitchell/interaction-kit/.github/workflows/install.yml@v1

  Build:
    uses: ianmitchell/interaction-kit/.github/workflows/build.yml@v1

  Test:
    runs-on: ubuntu-latest
    needs:
      - Install
      - Build
    steps:
      - name: Test
        run: |
          npm test
