name: Typecheck

on: [push, pull_request]

jobs:
  Install:
    uses: ianmitchell/interaction-kit/.github/workflows/install.yml@ee08c1f7f12daa96bbb815f6b510528f811d97a8

  Build:
    uses: ianmitchell/interaction-kit/.github/workflows/build.yml@ee08c1f7f12daa96bbb815f6b510528f811d97a8

  Typecheck:
    runs-on: ubuntu-latest
    needs:
      - Install
      - Build
    steps:
      - name: Typecheck
        run: |
          yarn typecheck
