name: Typecheck

on: [push, pull_request]

jobs:
  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Typecheck
        run: |
          npm run typecheck
