name: Typecheck

on: [push, pull_request]

jobs:
  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.2
          cache: yarn

      - name: Install
        env:
          CI: true
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Typecheck
        run: |
          yarn typecheck
