name: Typecheck

on: [push, pull_request]

jobs:
  Install:
    uses: ./.github/workflows/install.yml@v1

  Build:
    uses: ./.github/workflows/build.yml@v1

  Typecheck:
    runs-on: ubuntu-latest
    needs:
      - Install
      - Build
    steps:
      - name: Typecheck
        run: |
          yarn typecheck
